export const HEADER_AND_FOOTER_HEIGHT = 30; // px
export const TABLE_CELL_MIN_HEIGHT = 28; // px
export const TABLE_MIN_HEIGHT = 10 * (TABLE_CELL_MIN_HEIGHT + 2) + TABLE_CELL_MIN_HEIGHT + 2; // px
export const TABLE_MIN_HEIGHT_WITH_HEADER_AND_FOOTER =
  TABLE_MIN_HEIGHT + 2 + 2 * HEADER_AND_FOOTER_HEIGHT + 10; // px
